[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deforestation"
version = "0.1.0"
description = "Simple deforestation detection using spectral thresholds (SWIR/NIR or NIR-Red)"
readme = "README.md"
authors = [{name = "Your Name"}]
requires-python = ">=3.8"
dependencies = [
  "numpy",
  "rasterio",
  "scipy",
]

[project.scripts]
deforest = "deforestation.cli:main"

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["src"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["deforestation*"]
exclude = [
  "data*", "logs*", "tmp*", "outputs*", "outputs_70*", "outputs_20*",
  "deforestation*",  # exclude any stray folder/module named like this
]