
[project]
name = "defor"
version = "0.1.0"
description = "Simple deforestation detection (SWIR/NIR or NIR-RED) with a clean, testable design."
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name="Yan Cheng", email="chengyan2017@gmail.com" }]
dependencies = [
    "numpy>=1.22",
    "rasterio>=1.4.0",
    "typer>=0.9.0",
]

[project.scripts]
defor = "defor.cli:entrypoint"

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.ruff]
line-length = 100
target-version = "py39"

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true

# 👇 flat layout: only include the 'defor' package
[tool.setuptools.packages.find]
include = ["defor*"]
exclude = [
  "data*", "logs*", "tmp*", "outputs*", "outputs_70*", "outputs_20*",
  "deforestation*",  # exclude any stray folder/module named like this
]
